### ISSUE TITLE
Issue using ts-node directly from root of project

### ISSUE THREAD

**Issue by terminal-bash** [ThePrimeagen/vim-royale#6]
When I go to run `ts-node`, I get the following error:
```
➜  vim-royale git:(master) ts-node src/server/index.ts 
zsh: command not found: ts-node
```

I currently have to use the binary in the `node_modules/.bin` directory. This was an issue on both Linux (Ubuntu) and Windows.

**Comment by ThePrimeagen** [comment]
Yes you have to do that no matter what.  ts-node needs to be in your $PATH to be used the way you are referencing it.  I would suggest doing `npx ts-node` or `node ./node_modules/.bin/ts-node`.  The latter is the way I do it because `npx` is a piece of shit just like npm and all their devs.
